# Generated by Django 4.2.3 on 2023-08-08 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urdu',
            old_name='choice_text',
            new_name='Urdu_text',
        ),
        migrations.RenameField(
            model_name='urdu',
            old_name='question',
            new_name='word',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='question_text',
            new_name='word_text',
        ),
    ]
